version: '3.8'

services:
  api:
    build: .
    container_name: node_api
    ports:
      - "3750:3750" # Porta para a API
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=aluguel_livros
      - PORT=3750
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3307:3306" # Porta para o banco de dados
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: aluguel_livros
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
